file_watching_rate_seconds = 0.3

[extensions]
raw = ["txt"]
texture = ["jpg", "png"]
mesh = ["glb", "gltf"]
audio = ["ogg", "wav"]

[meshes]
use_meshlets = false
storage = "Glb"

[textures]
filter = "Linear"
